### ISSUE TITLE
LVGL Not Displaying on Screen with EK-RA8D1 and FreeRTOS

### ISSUE THREAD

**Issue by codeph112** [lvgl/lv_port_renesas_ek-ra8d1_gcc#13]
I am using E2 Studio version 5.4 and attempting to recreate an LVGL project with FreeRTOS using only the source code, without including any demos, examples, or additional components. The project is set up as a clean project.

1. The C/C++ build configuration is correctly set up.
2. The code compiles and runs successfully.
3. At startup, the display backlight blinks once but then remains black.
4. No errors or faults are reported.

Despite these indications, nothing is displayed on the screen. Could you please assist in identifying the issue?
[lv_](https://github.com/lvgl/lv_port_renesas_ek-ra8d1) working perfectly without any issue.

TestProject - 
https://github.com/codeph112/lvgl-test-project

**Comment by kisvegabor** [comment]
Just to confirm, does this repo as it is work well? Maybe you meant this by

> lv_ working perfectly without any issue.

**Comment by codeph112** [comment]
Thank you for providing this great repository. I have been working with /lv_port_renesas_ek-ra8d1 and can confirm that it works perfectly with E2 Studio 5.3. However, I have noticed that the CPU usage is relatively high, ranging from 50 to 60% when running lv_example_get_started_1.

For my final project, I need to use multiple threads and therefore need to optimize the CPU usage. Any advice or suggestions to help optimize CPU usage would be greatly appreciated.

**Comment by kisvegabor** [comment]
Fortunately the high CPU usage is just a measurement issue. I'll add a fix today. 

@becseya will take a look at the project creation issue.

**Comment by codeph112** [comment]
@kisvegabor,

I have completed testing with /lv_port_renesas_ek-ra8d1 on E2 Studio 5.4, and it is functioning perfectly. The high CPU usage mentioned in the previous reply appears to be a measurement issue, so we can set that aside for now as we await your resolution.

Today, I will attempt to recreate a clean project from the source, incorporating the updates made by @becseya, including the screen rotation feature. I will keep you informed about the results.

@becseya, if you have any insights regarding the last issue I mentioned, your guidance would be greatly appreciated.

**Comment by kisvegabor** [comment]
@codeph112 I've updated project, not the benchmark result is: 
- CPU usage: 21%
- Avg FPS: 24FPS
- Avg. time (render + flush) = 35 ms (24 + 11)

All these with VSYNC (no tearing).

LVGL is also updated, so  you can use LVGL's GLCDC driver.

I forgot that @becseya is on vacation, so I'll look into your project. Please push your latest version to to [your repo](https://github.com/codeph112/lvgl-test-project).

**Comment by codeph112** [comment]
@kisvegabor 

I have updated the repository with the latest changes. **_Thank you_** very much for your attention.

**Comment by codeph112** [comment]
@kisvegabor

I forgot to enable the SDRAM from the BSP properties, but it's working now.

Thank you so much for your support.

I haven't tested the touch functionality and all the features of LVGL yet, but I will do so and provide updates accordingly.

**Comment by kisvegabor** [comment]
Oh, it's great that you found the root of the issue. Congratulations! 

I'm sorry that we couldn't help earlier. :slightly_frowning_face:

**Comment by codeph112** [comment]
Hello @kisvegabor,

I'm planning to replace the Focus LCD currently used with the RA8D1 Renesas GLCD with a Waveshare display, specifically this model: [7-inch DSI LCD from Waveshare](https://www.waveshare.com/7inch-dsi-lcd.htm). This new LCD includes an ICN6211 bridge and a GT911 touch controller.

I found Linux driver configurations for the ICN6211 here: [Linux ICN6211 Driver on GitHub](https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/bridge/chipone-icn6211.c). Could you guide me on the necessary changes in FSP MPI, DSI, and GLCD configurations to support this display? Additionally, I need to know how to integrate new LCD drivers into LVGL and any required modifications in LVGL code itself to accommodate this new display setup.
