### ISSUE TITLE
lv_img_set_angle not working under 9.2

### ISSUE THREAD

**Issue by FloHomi** [lvgl/lv_port_renesas_ek-ra8d1_gcc#16]
Hi,
rotating an image does not work on this project with 9.2
The image is okay at 0° and then dissapears.
the angle is counted up by 0.1° but only shown in whole degrees.

![1725953818356](https://github.com/user-attachments/assets/98f3a9f3-c682-4c99-9872-1b4e50f35f74)
![1725953818343](https://github.com/user-attachments/assets/dc9a15a4-2da6-40ec-b20b-ad42bfcce08f)
![1725953818331](https://github.com/user-attachments/assets/b7e89c02-3ad6-4625-9c51-a57b78712010)

I Think that it might has something to do with the #define LV_USE_OS   LV_OS_NONE 
Because in the Visual Studio Simulator running the same 9.2, rotation works just fine.

I tried to set the LV_OS_FREERTOS, but that does not work currently.
Maybe because of the issue with [issue #6803](https://github.com/lvgl/lvgl/pull/6803) or simmilar

Best regards Florian

**Comment by kisvegabor** [comment]
Could you send me the the image as C array the you have used?

**Comment by FloHomi** [comment]
[img_moca_400x216.zip](https://github.com/user-attachments/files/16959886/img_moca_400x216.zip)

**Comment by kisvegabor** [comment]
Thank you! 

Last question: do you use Dave2D?

**Comment by kisvegabor** [comment]
Ah, it's in I4 format. Please enable `LV_BIN_DECODER_RAM_LOAD`. It's required to load the whole indexed image to RAM in order to rotate it.

**Comment by FloHomi** [comment]
I tried that, but then no image at all is shown

**Comment by FloHomi** [comment]
I now tried a 565 image an that works. It appears to be something with the I4.

**Comment by kisvegabor** [comment]
Dave2D was incorrectly taking all the image rendering. Could you try with these changes:
```diff
diff --git a/src/draw/renesas/dave2d/lv_draw_dave2d.c b/src/draw/renesas/dave2d/lv_draw_dave2d.c
index 039b147a7..faef05ce6 100644
--- a/src/draw/renesas/dave2d/lv_draw_dave2d.c
+++ b/src/draw/renesas/dave2d/lv_draw_dave2d.c
@@ -243,6 +243,12 @@ static int32_t _dave2d_evaluate(lv_draw_unit_t * u, lv_draw_task_t * t)
 
         case LV_DRAW_TASK_TYPE_IMAGE: {
 #if USE_D2
+            lv_draw_image_dsc_t * dsc = t->draw_dsc;
+            if(dsc->header.cf == LV_COLOR_FORMAT_RGB565 ||
+               dsc->header.cf == LV_COLOR_FORMAT_RGB888 ||
+               dsc->header.cf == LV_COLOR_FORMAT_XRGB8888 ||
+               dsc->header.cf == LV_COLOR_FORMAT_ARGB8888)
+
                 t->preferred_draw_unit_id = DRAW_UNIT_ID_DAVE2D;
                 t->preference_score = 0;
 #endif
diff --git a/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c b/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c
index 98fb80609..a0acaf68b 100644
--- a/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c
+++ b/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c
@@ -106,9 +106,10 @@ d2_u32 lv_draw_dave2d_lv_colour_fmt_to_d2_fmt(lv_color_format_t colour_format)
             d2_lvgl_mode = d2_mode_rgb565;
             break;
         case(LV_COLOR_FORMAT_RGB888):
-            d2_lvgl_mode = d2_mode_argb8888; //?
+            d2_lvgl_mode = d2_mode_rgb888; //?
             break;
         case(LV_COLOR_FORMAT_ARGB8888):
+        case(LV_COLOR_FORMAT_XRGB8888):
             d2_lvgl_mode = d2_mode_argb8888;
             break;
```

This way the software renderer will rotate the image, but to load a 400x216 image to RAM (to allow rotating it) you will need 400x216x4=337kB RAM. So probably RGB565 is a better choice in this case.

**Comment by kisvegabor** [comment]
Could you confirm if these changes were working on your side too?
