### ISSUE TITLE
[ek_ra8d1] The Analytics screen of the widgets demo is flickering with O0 optimization

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_renesas_ek-ra8d1_gcc#2]
As the tile says

**Comment by jeremy-baker** [comment]
when vsync_wait is used with lv_display_set_flush_wait_cb(), with low compiler optimisation, vsync_wait() returns before the GLCDC has switched the buffer it is displaying. In this case, vsync_wait() needs to wait for the GLCDC to switch buffers, then wait for a VSYNC interrupt.

**Comment by jeremy-baker** [comment]
I pushed a fix to the project for the flicker issue.

https://github.com/lvgl/lv_renesas/commit/3068a48209a1f1440547c148321660f10b5a9fc4

**Comment by kisvegabor** [comment]
It working well now, thank you!
