### ISSUE TITLE
[lv_ek_ra8d1] arm-none-eabi-gdb not found

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_renesas_ek-ra8d1_gcc#7]
After updating to the latest version I got this error on attempting to Debug:
![image](https://github.com/lvgl/lv_renesas/assets/7599318/b3d3c05c-3d1b-4ab0-9474-72cdfa06b788)

BSP config:
![image](https://github.com/lvgl/lv_renesas/assets/7599318/16021fe7-354a-4377-9dec-f1e8b378d65c)

Toolchain:
![image](https://github.com/lvgl/lv_renesas/assets/7599318/a0247325-389f-4fe9-82a5-25354cbed748)
![image](https://github.com/lvgl/lv_renesas/assets/7599318/e262338a-a4f6-4b21-94dc-dd775ec9613d)

I've checked `arm-none-eabi-gdb` is in the bin folder of the selected compiler.

@jeremy-baker do you have any ideas?

**Comment by jeremy-baker** [comment]
The version of arm-none-eabi-gdb used by the debugger is not provided by the compiler, there is a version provided by the debug components shipped with the FSP. This is in the e2studio support area (help->about e2studio->installation details->Support folders then click the link for the "e2studio support area" in the DebugComp/RA folder in the e2studio support area :- 
![image](https://github.com/lvgl/lv_renesas/assets/54705580/65f89199-88eb-488a-af5c-a26998fe17bb)

**Comment by kisvegabor** [comment]
When I try to run `arm-none-eabi-gdb` I get:
```
~/.eclipse/com.renesas.platform_175529464/DebugComp/RA $./arm-none-eabi-gdb 
./arm-none-eabi-gdb: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

I've checked that `libpython3.10.so.1.0` exists.

**Comment by jeremy-baker** [comment]
These are the libraries it uses on my system :- 
![image](https://github.com/lvgl/lv_renesas/assets/54705580/dc4611bb-d5ff-43d5-9ee4-06abeaccd1b7)

**Comment by kisvegabor** [comment]
I've reinstalled python3.10 from source and now it's working. Thank you! :slightly_smiling_face: 

So the debugger is working the rendered image scrambled. Does it work on your end with the latest LVGL master?

**Comment by kisvegabor** [comment]
The issue was on my end.

**Comment by jeremy-baker** [comment]
If I use Direct rendering, the image is broken, if I use FULL or Partial rendering the image on the screen is good.
